name: "Conan dependencies"
description: "Gets conan dependencies"
inputs:
  JF_ACCESS_TOKEN:
    description: Access token for conan repo
    required: true
  JF_CONAN_URL:
    description: URL of conan repo
    required: true
  BUILD_TYPE:
    description: CMake Build Type
    required: false
    default: Release

runs:
  using: "composite"
  steps:
    - name: Install Conan dependencies
      shell: bash
      run: |
        pip3 install "conan"

        conan config install https://github.com/BigGeo-GIV/bg-conan.git -t git

        if [ ${{ runner.os }} = macOS ]; then
          export PATH=/Users/runner/hostedtoolcache/Python/3.10.11/arm64/bin:/Users/runner/hostedtoolcache/Python/3.10.11/arm64:/Users/runner/hostedtoolcache/cmake/3.27.9/arm64/cmake-3.27.9-macos-universal/CMake.app/Contents/bin:/bin:/Users/runner/.local/bin/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools
        fi

        conan remote add bg-conan ${{ inputs.JF_CONAN_URL }}
        conan remote login -p ${{ inputs.JF_ACCESS_TOKEN }} bg-conan github_workflow
        conan install . -s build_type=${{ inputs.BUILD_TYPE }} -b=missing -pr:a=${{ runner.os }}
        conan upload "*" -r bg-conan -c
