name: "Conan dependencies"
description: "Gets conan dependencies"
inputs:
  JF_ACCESS_TOKEN:
    description: Access token for conan repo
    required: true
  PYTHON_DEPS:
    description: Get Python dependencies
    required: false
    default: false
  BUILD_TYPE:
    description: CMake Build Type
    required: false
    default: Release

runs:
  using: "composite"
  steps:
    - name: Install Conan dependencies
      shell: bash
      run: |
        if [ ${{ runner.os }} = macOS ]; then
          export CC=/usr/local/opt/llvm@16/bin/clang
          export CXX=/usr/local/opt/llvm@16/bin/clang++
        fi

        poetry run invoke setup
        poetry run conan remote login -p ${{ inputs.JF_ACCESS_TOKEN }} bg-conan github_workflow
        
        if [ ${{ inputs.PYTHON_DEPS }} = true ]; then
          poetry run invoke deps --buildtype Release --python
        else
          poetry run invoke deps --buildtype ${{ inputs.BUILD_TYPE }} 
        fi
        
        poetry run conan upload "*" -r bg-conan -c
