name: "Conan dependencies"
description: "Gets conan dependencies"
inputs:
  JF_ACCESS_TOKEN:
    description: Access token for conan repo
    required: true
  JF_CONAN_URL:
    description: URL of conan repo
    required: true
  BUILD_TYPE:
    description: CMake Build Type
    required: false
    default: Release

runs:
  using: "composite"
  steps:
    - name: Install Conan dependencies
      shell: bash
      run: |
        pip3 install "conan"

        conan config install git@github.com:BigGeo-GIV/bg-ci.git -a "-b conan-profiles --single-branch"

        conan remote add bg-conan ${{ inputs.JF_CONAN_URL }}
        conan user -p ${{ inputs.JF_ACCESS_TOKEN }} -r bg-conan github_workflow
        conan install . -s build_type=${{ inputs.BUILD_TYPE }} -b missing -pr  ${{ runner.os }}
        conan upload "*" --all -r bg-conan -c
