name: "Conan dependencies"
description: "Gets conan dependencies"
inputs:
  JF_ACCESS_TOKEN:
    description: Access token for conan repo
    required: true
  PYTHON_DEPS:
    description: Get Python dependencies
    required: false
    default: false
  BUILD_TYPE:
    description: CMake Build Type
    required: false
    default: Release

runs:
  using: "composite"
  steps:
    - name: Install Conan dependencies
      shell: bash
      run: |
        if [ ${{ runner.os }} = macOS ]; then
          export CC=/usr/local/opt/llvm@16/bin/clang
          export CXX=/usr/local/opt/llvm@16/bin/clang++
        fi

        invoke setup
        conan remote login -p ${{ inputs.JF_ACCESS_TOKEN }} bg-conan github_workflow

        if [ ${{ inputs.PYTHON_DEPS }} = true ]; then
          invoke deps --buildtype Release
        else
          invoke deps --buildtype ${{ inputs.BUILD_TYPE }}
        fi

        conan upload "*" -r bg-conan -c
