name: Create Image

on:
  workflow_call:
    inputs:
      dev_version:
        description: 'Deploy as dev version?'
        required: true
        type: boolean
      name:
        required: true
        type: string
      sfName:
        description: 'Name to use for sf.'
        required: false
        type: string
        default: ${{ inputs.name }}

    secrets:
      GH_ACCESS:
        required: true
      JF_ACCESS_TOKEN:
        required: true
      JF_CONAN_URL:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: { submodules: recursive }

    - uses: actions/checkout@v3
      with:
        repository: BigGeo-GIV/bg-ci
        ref: v3.x
        path: bg-ci
        token: ${{ secrets.GH_ACCESS }}

    - name: Get version
      id: version
      run: |
        if [ ${{ inputs.dev_version }} = true ]; then
          prefix=dev-
          stageOrLatest=stage
        else
          stageOrLatest=latest
        fi
        ver=$(python3 bg-ci/GetVersion.py version.json ${{ inputs.dev_version }})
        echo "VERSION=${prefix}${ver}" >> "$GITHUB_OUTPUT"
        echo "STAGE_OR_LATEST=${stageOrLatest}" >> "$GITHUB_OUTPUT"

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Docker log in
      uses: BigGeo-GIV/bg-ci/.github/actions/docker-login@v3.x
      with:
        DOCKER_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
        DOCKER_PASS: ${{ secrets.SNOWFLAKE_PASSWORD_CA_CENTRAL }}
        DOCKER_USER_OREGON: ${{ secrets.SNOWFLAKE_USERNAME }}
        DOCKER_PASS_OREGON: ${{ secrets.SNOWFLAKE_PASSWORD_OREGON }}
        BG_SEARCH_DOCKER_REGISTRY_AZ_SERVER: ${{ secrets.BG_SEARCH_DOCKER_REGISTRY_AZ_SERVER }}
        BG_SEARCH_DOCKER_REGISTRY_AZ_NAME: ${{ secrets.BG_SEARCH_DOCKER_REGISTRY_AZ_NAME }}
        BG_SEARCH_DOCKER_REGISTRY_AZ_PSWD: ${{ secrets.BG_SEARCH_DOCKER_REGISTRY_AZ_PSWD }}

    - name: Build and push bg-search to Azure
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./
        tags: |
          crbgsearchdevwestus001.azurecr.io/${{ inputs.name }}:${{ steps.version.outputs.VERSION }}
          crbgsearchdevwestus001.azurecr.io/${{ inputs.name }}:${{ steps.version.outputs.STAGE_OR_LATEST }}
        build-args: |
          CONAN_USER=github_workflow
          CONAN_PSWD=${{ secrets.JF_ACCESS_TOKEN }}

    - name: Build and push bg-search to Snowflake
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./
        tags: |
          eqcqgux-biggeoawsoregon.registry.snowflakecomputing.com/spdemo/data_schema/alcyone_repository/${{ inputs.sfName }}:${{ steps.version.outputs.VERSION }}
          eqcqgux-biggeoawsoregon.registry.snowflakecomputing.com/spdemo/data_schema/alcyone_repository/${{ inputs.sfName }}:${{ steps.version.outputs.STAGE_OR_LATEST }}
        build-args: |
          CONAN_USER=github_workflow
          CONAN_PSWD=${{ secrets.JF_ACCESS_TOKEN }}
