name: Update Dependencies

on:
  workflow_call:
    secrets:
      GH_ACCESS:
        required: true

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_ACCESS }}

    - uses: actions/checkout@v3
      with:
        repository: BigGeo-GIV/bg-ci
        ref: main
        path: bg-ci

    - name: Install Python
      uses: actions/setup-python@v4
      with: { python-version: "3.8" }

    - name: Update dependencies
      id: bump
      run: |
        pip3 install "conan<2"
        pip3 install semantic_version

        body=$(python3 bg-ci/UpdateDeps.py)
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "BODY<<$EOF" >> $GITHUB_OUTPUT
        echo "${body}" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT

        myDate=$(date +'%Y-%m-%d')
        echo "DATE=${myDate}" >> $GITHUB_OUTPUT

    - uses: peter-evans/create-pull-request@v5
      with:
        add-paths: dependencies.json
        commit-message: Update dependencies
        committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        signoff: false
        branch: dependencies-${{ steps.bump.outputs.DATE }}
        delete-branch: true
        title: Update dependencies ${{ steps.bump.outputs.DATE }}
        body: ${{ steps.bump.outputs.BODY }}

    - name: Commit to trigger CI on PR
      id: commit
      env:
        GH_TOKEN: ${{ secrets.GH_ACCESS }}
      run: |
        if $( git ls-remote --exit-code --heads origin dependencies-${{ steps.bump.outputs.DATE }} > /dev/null); then
          echo "PUSH=1" >> $GITHUB_OUTPUT
          git pull origin dependencies-${{ steps.bump.outputs.DATE }}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Trigger CI"
        fi

    - name: Push changes
      if: steps.commit.outputs.PUSH
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_ACCESS }}
        branch: dependencies-${{ steps.bump.outputs.DATE }}
