name: Update Dependencies

on:
  workflow_call:
    secrets:
      GH_ACCESS:
        required: true
      JF_ACCESS_TOKEN:
        required: true
      JF_CONAN_URL:
        required: true

jobs:
  update-deps:
    runs-on: ubuntu-latest
    env: {CONAN_REVISIONS_ENABLED: 1}

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_ACCESS }}
        repository: ${{ github.repository }}
        ref: ${{ github.head_ref }}

    - uses: actions/checkout@v3
      with:
        repository: BigGeo-GIV/bg-ci
        ref: main
        path: bg-ci

    - name: Install Python
      uses: actions/setup-python@v4
      with: { python-version: "3.8" }

    - name: Update dependencies script
      id: bump
      run: |
        pip3 install "conan<2"
        pip3 install semantic_version

        conan remote add bg-conan ${{ secrets.JF_CONAN_URL }}
        conan user -p ${{ secrets.JF_ACCESS_TOKEN }} -r bg-conan github_workflow

        if body=$(python3 bg-ci/UpdateDeps.py bg-conan); then
          echo "GO=1" >> $GITHUB_OUTPUT
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "BODY<<$EOF" >> $GITHUB_OUTPUT
          echo "${body}" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push updates
      if: steps.bump.outputs.GO
      id: commit
      env:
        GH_TOKEN: ${{ secrets.GH_ACCESS }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add dependencies.json
        git commit -m "Update dependencies"
        git push

    # - name: Push changes
    #   uses: ad-m/github-push-action@master
