name: Merge Back

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      GH_ACCESS:
        required: true

jobs:
  merge-back:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: BigGeo-GIV/bg-ci
        ref: v3.x
        path: bg-ci

    - name: Install Python
      uses: actions/setup-python@v4
      with: { python-version: "3.10" }

    - name: Create merge-back PR
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        branchAry=($(echo ${{ github.ref_name }} | tr "-" "\n")) && suffix=${branchAry[1]}
        if [ -n "${suffix}" ]; then
          suffix=-${suffix}
        fi

        newVer=$(python3 bg-ci/GetVersion.py version.json false)
        git checkout -b merge-back${suffix}
        git push -u origin merge-back${suffix} --force
        gh pr create -B develop${suffix} -t "v${newVer} merge back to develop" -b ""
