name: Deploy

on:
  workflow_call:
    inputs:
      docker_name:
        description: 'Name of the docker github-artifact to use for deployment'
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      GH_ACCESS:
        required: true

jobs:
  deploy:
    env:
      CONAN_REVISIONS_ENABLED: 1
      service_name: "'Bg_auto'"
      compute_pool: "'LAND_NA_LEASE'"
      db_name: 'SPDEMO'
      schema_name: 'DATA_SCHEMA'
      spec_file: "'biggeo-b.yaml'"
      table_name: "'LAND_NA_LEASE'"
      geomtype: "'polygon'"

    runs-on: ubuntu-22.04

    steps:
      - name: Download docker files
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.docker_name }}
          path: ./Docker

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Docker login to Azure Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_AZ_SERVER}}
          username: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_AZ_NAME}}
          password: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_AZ_PSWD}}
      - name: Docker login to Snowflake Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SERVER}}
          username: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_NAME}}
          password: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_PSWD}}
      - name: Docker login to S&P Snowflake Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_SERVER}}
          username: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_NAME}}
          password: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_PSWD}}

      - name: Build and push bg-search docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./Docker/
          tags: |
            crbgsearchdevwestus001.azurecr.io/bg-search-test:${{steps.version.outputs.VERSION}}
            eqcqgux-biggeoaws.registry.snowflakecomputing.com/alcyone_db/data_schema/alcyone_repository/bg_server:${{steps.version.outputs.VERSION}}
            ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_SERVER}}/bg_server:${{steps.version.outputs.VERSION}}
          build-args: REACT_APP_ENV=prod
