name: Deploy

on:
  workflow_call:
    inputs:
      docker_name:
        description: 'Name of the docker github-artifact to use for deployment'
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      GH_ACCESS:
        required: true

jobs:
  deploy:
    env:
      CONAN_REVISIONS_ENABLED: 1
      service_name: "'Bg_auto'"
      compute_pool: "'LAND_NA_LEASE'"
      db_name: 'SPDEMO'
      schema_name: 'DATA_SCHEMA'
      spec_file: "'biggeo-b.yaml'"
      table_name: "'LAND_NA_LEASE'"
      geomtype: "'polygon'"

    runs-on: ubuntu-22.04

    steps:
      - name: Download docker files
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.docker_name }}
          path: ./Docker

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Docker login to Azure Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_AZ_SERVER}}
          username: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_AZ_NAME}}
          password: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_AZ_PSWD}}
      - name: Docker login to Snowflake Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SERVER}}
          username: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_NAME}}
          password: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_PSWD}}
      - name: Docker login to S&P Snowflake Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_SERVER}}
          username: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_NAME}}
          password: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_PSWD}}

      - name: Build and push bg-search docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./Docker/
          tags: |
            crbgsearchdevwestus001.azurecr.io/bg-search-test:${{ inputs.version }}
            eqcqgux-biggeoaws.registry.snowflakecomputing.com/alcyone_db/data_schema/alcyone_repository/bg_server:${{ inputs.version }}
            ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_SERVER}}/bg_server:${{ inputs.version }}
          build-args: REACT_APP_ENV=prod

  snowflake:
    needs: deploy
    name: Snowflake Bg-search deployment
    uses: BigGeo-GIV/snowflake-spcs-config/.github/workflows/SPCS_File_Deploy.yml@main
    with:
      version: ${{ inputs.version }}

    # - name: Snowflake Query Action
    #   id: snowflake
    #   uses: anecdotes-ai/snowflake-query@v1.2
    #   env:
    #     bg_version: '${{steps.version.outputs.VERSION}}'
    #   with:
    #     # Username for Snowflake DB
    #     snowflake_username: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_NAME}}
    #     # Password for Snowflake DB
    #     snowflake_password: ${{secrets.BG_SEARCH_DOCKER_REGISTRY_SF_SP_PSWD}}
    #     # Account name for Snowflake DB. Your account name is the full/entire string to the left of snowflakecomputing.com.
    #     snowflake_account: 'kyb07147'
    #     # Warehouse as context
    #     snowflake_warehouse: 'BIGGEO'
    #     # Set user role
    #     snowflake_role: 'ALCYONE_ROLE'
    #     # List of SQL queries, seperated by ;
    #     queries: 'CALL ${{env.db_name}}.${{env.schema_name}}.BigGeoDeployment(service_name=>${{env.service_name}},compute_pool=>${{env.compute_pool}},bg_version=>''${{steps.version.outputs.VERSION}}'',db_name=>''${{env.db_name}}'',schema_name=>''${{env.schema_name}}'', spec_file => ${{env.spec_file}}, table_name=>${{env.table_name}}, geomtype => [${{env.geomtype}}])'
    #     # Whether to run the queries sync (default is async)
    #     # sync: # optional