name: Release

on:
  workflow_call:
    inputs:
      commitSHA:
        required: true
        type: string
    secrets:
      GH_ACCESS:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          branchAry=($(echo ${{ github.ref_name }} | tr "-" "\n")) && suffix=${branchAry[1]}
          if [ -n "${suffix}" ]; then
            suffix=-${suffix}
          fi

          git checkout ${{ inputs.commitSHA }}
          git checkout -b staging${suffix}
          git push -u origin staging${suffix} --force
          gh pr create -B main${suffix} -t "release " -b ""
          gh workflow run version-bump.yml --ref staging${suffix}
