name: Version Bump

on:
  workflow_call:
    secrets:
      GH_ACCESS:
        required: true

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_ACCESS }}

    - uses: actions/checkout@v3
      with:
        repository: BigGeo-GIV/bg-ci
        ref: workflow-dev
        path: bg-ci
        token: ${{ secrets.GH_ACCESS }}

    - name: Install Python
      uses: actions/setup-python@v4
      with: { python-version: "3.10" }

    - name: Bump version
      env:
        GH_TOKEN: ${{ github.token }}
      # We do different things when bumping version on a PR vs on a branch commit; the workflow_dispatch
      # conditional is how we detect these situations and behave accordingly
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

        if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
          git checkout ${{ github.head_ref }}
          gh pr view --json commits > prevMsgs.json
          file=prevMsgs.json
          dev=false
          messageSuffix=""
        else
          git log -1 --pretty=%B > prevMsg.txt
          file=prevMsg.txt
          dev=true
          messageSuffix=" - $(cat prevMsg.txt)"
        fi

        bumps=$(python3 bg-ci/BumpVersion.py version.json ${file} ${dev})

        git add version.json
        if git commit -m "${bumps}${messageSuffix}"; then
          git pull
          git push
        fi
