name: Version Bump

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      GH_ACCESS:
        required: true

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_ACCESS }}

    - uses: actions/checkout@v3
      with:
        repository: BigGeo-GIV/bg-ci
        ref: v2
        path: bg-ci
        token: ${{ secrets.GH_ACCESS }}

    # - name: Check for manual version change
    #   id: check
    #   run: |
    #     if git diff --name-only HEAD^ HEAD | grep version.json; then
    #       echo version and source changed: no need to bump
    #     else
    #       echo "GO=1" >> $GITHUB_OUTPUT
    #     fi

    - name: Install Python
      uses: actions/setup-python@v4
      with: { python-version: "3.10" }

    - name: Bump version
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

        if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
          git checkout ${{ github.head_ref }}
          gh pr view --json commits > prevMsgs.json
          file=prevMsgs.json
          dev=false
          messagePrefix="v"
          messageSuffix=""
        else
          git log -1 --pretty=%B > prevMsg.txt
          file=prevMsg.txt
          dev=true
          messagePrefix="dev"
          messageSuffix=" - $(cat prevMsg.txt)"
        fi

        didBump=$(python3 bg-ci/BumpVersion.py version.json ${file} ${{ inputs.name }} ${dev})

        if [ "${didBump}" = "bump" ]; then
          git add version.json
          newVer=$(python3 bg-ci/GetVersion.py version.json ${{ inputs.name }} ${dev})
          git commit -m "${messagePrefix}${newVer}${messageSuffix}"
          git pull
          git push
        fi
